config/routes.rb
Rails.application.routes.draw do
  root to: "agents#random_agent"

  namespace :uploaded_transactions do
    post 'import'
  end

  resources :agents do
    resources :uploaded_transactions
  end
end

app/models/agent.rb
class Agent < ApplicationRecord
  has_many :uploaded_seller_transactions, class_name: "UploadedTransaction", foreign_key: :listing_agent_id
  has_many :uploaded_buyer_transactions, class_name: "UploadedTransaction", foreign_key: :selling_agent_id

  def all_transactions
    UploadedTransaction.where("listing_agent_id = ? OR selling_agent_id = ?", id, id).order(
      "case when property_type in ('land', 'mobile_home') then 0 else 1 end desc, selling_date desc"
    )
  end

  def recent_transactions
    all_transactions.where("selling_date > ?", 6.months.ago)
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/uploaded_transaction.rb
class UploadedTransaction < ApplicationRecord
  belongs_to :listing_agent, required: false, class_name: "Agent"
  belongs_to :selling_agent, required: false, class_name: "Agent"

  scope :single_family_homes, -> { where(property_type: "single_family_home") }
  scope :sold, -> { where(status: "sold") }
  validates :address, uniqueness: { scope: [:selling_date, :zip] }


  def full_address
    "#{address}, #{city}, #{state} #{zip}"
  end

  require 'csv'

  def self.import(file)

    CSV.foreach(file.path, headers: true) do |row|
      UploadedTransaction.create! row.to_hash
    end
  end
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  def show
    @agent = Agent.find(params[:id])
    @uploaded_transactions = @agent.all_transactions.paginate(:page => params[:page])
  end

  def random_agent
    redirect_to agent_path(Agent.all.sample)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/uploaded_transactions_controller.rb
class UploadedTransactionsController < ApplicationController
  def new
    @agent = Agent.find(params[:agent_id])
    @uploaded_transaction = @agent.all_transactions.new
  end

  def create
    agent = Agent.find(params[:agent_id])
    updated_params = uploaded_transaction_params

    if params.key?('selling_agent_id') && params.key?('listing_agent_id')
      updated_params['selling_agent_id'] = params[:agent_id]
      updated_params['listing_agent_id'] = params[:agent_id]
    elsif !params.key?('selling_agent_id') && params.key?('listing_agent_id')
      updated_params['listing_agent_id'] = params[:agent_id]
    else
      updated_params['selling_agent_id'] = params[:agent_id]
    end

    uploaded_transaction = agent.all_transactions.create(updated_params)

    if uploaded_transaction.save
      redirect_to agent_path(agent), notice: "Transaction saved!"
    else
      render "new"
    end
  end

  def import
    UploadedTransaction.import(params[:file])
    redirect_to root_url, notice: "CSV imported!"
  end
  private

  def uploaded_transaction_params
    params.require(:uploaded_transaction).permit(:address, :city, :state, :zip, :listing_agent, :listing_price, :listing_date, :selling_price, :selling_agent, :selling_date, :status, :property_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agents/show.html.slim
h1 = @agent.full_name
p = @agent.bio
.row style=("padding: inherit;")

  = link_to "Add Transaction", new_agent_uploaded_transaction_path(@agent), class: "btn btn-primary"

.row style=("padding: inherit;")
  = form_tag uploaded_transactions_import_path, multipart: true do
    = file_field_tag :file
    = submit_tag "Bulk Upload", class: "btn btn-primary"

h3 Recent Transactions
= will_paginate @uploaded_transactions
table
  thead
    tr
      th Address
      th Listed
      th Listing Price
      th Sold
      th Selling Price
      th
  tbody
    - @uploaded_transactions.each do |uploaded_transaction|
      tr
        td = uploaded_transaction.full_address
        td = uploaded_transaction.listing_date
        td = uploaded_transaction.listing_price
        td = uploaded_transaction.selling_date
        td = uploaded_transaction.selling_price

= will_paginate @uploaded_transactions

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uploaded Transactions Manager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="#">Agents & Transactions</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
             <li class="nav-item dropdown active">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Agents</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <% Agent.all.each do |agent| %>
                  <a class="dropdown-item" href="<%= agent_path(agent) %>"><%= agent.full_name %></a>
                <% end %>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/uploaded_transactions/new.html.slim
h1 New Transaction

= form_for [@agent, @uploaded_transaction] do |f|
  .form-group
    = f.label :address
    = f.text_field :address, class: "form-control"
  .form-group
    = f.label :city
    = f.text_field :city, class: "form-control"
  .form-group
    = f.label :state
    = f.text_field :state, class: "form-control"
  .form-group
    = f.label :zip
    = f.text_field :zip, class: "form-control"
  .form-group
    = f.label :listing_date
    = f.text_field :listing_date, class: "form-control"
  .form-group
    = f.label :listing_price
    = f.text_field :listing_price, class: "form-control"
  .form-group
    = f.label :selling_date
    = f.text_field :selling_date, class: "form-control"
  .form-group
    = f.label :selling_price
    = f.text_field :selling_price, class: "form-control"
  .form-group
    = f.label :status
    = f.select :status, %w(sold pending closed cancelled expired active)
  .form-group
    = f.label :property_type
    = f.select :property_type, %w(condo single_family_home multi_family_home commercial mobile_home land)
  .form-group
    = f.label :seller
    = check_box_tag "selling_agent_id", @agent.id, true
  .form-group
    = f.label :buyer
    = check_box_tag "listing_agent_id", @agent.id, false

  = f.submit "Save", class: "btn btn-primary"